Repository pagarme/emblematic-icons, pull requests merged in 2019-07, with the labels that each got.

#18 Add Menu Collapsed and Menu Not Collapsed
  svg/MenuCollapsed24.svg
  svg/MenuCollapsed32.svg
  svg/MenuNotCollapsed24.svg
  svg/MenuNotCollapsed32.svg
Labels: pilot, review-needed

#19 Update version
  package.json
Labels: cos:standard, review-needed

#20 Add 24x24 Menu Collapse and Menu Not Collapse
  svg/MenuCollapsed24.svg
  svg/MenuCollapsed32.svg
  svg/MenuNotCollapsed24.svg
  svg/MenuNotCollapsed32.svg
Labels: bug, devs, pilot

#21 Update version
  package.json
Labels: bug, devs, pilot
