Repository pagarme/emblematic-icons, pull requests merged in 2019-01, with the labels that each got.

#13 chore: bump version to 0.6.0
  package.json
Labels: review-needed

#14 add/bankAccountIcon: add Bank Account Icon
  svg/BankAccount24.svg
  svg/BankAccount32.svg
Labels: pilot, review-needed

#15 Refactor bancAccountIcon icon fill
  svg/BankAccount24.svg
  svg/BankAccount32.svg
Labels: bug, review-needed

#16 chore: bump version to 0.6.1
  package.json
Labels: review-needed
